### ISSUE TITLE
Add account restrictions

### ISSUE THREAD

**Issue by Peersyst** [nemgrouplimited/symbol-desktop-wallet#748]
**Task list**

- [x] Design mocks

- [ ] UX/UI for the modal, form and list

- [ ] Logic for restriction list (mosaics, address and operation)

- [ ] Remove restriction logic (mosaic, address and operation)

- [ ] Add new restriction logic

**Mock up**
![account-restriction-mockups](https://user-images.githubusercontent.com/54996852/100609612-9490ac00-330e-11eb-94f2-e7e6bd637eee.jpg)

**Comment by cryptoBeliever** [comment]
Closing.
